# FINAL_DEV/terrain-booking-system/kubernetes/laravel-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
type: Opaque
data:
  db-password: SGVsbG9AMTIz  # base64 encoded "Hello@123"
  app-key: <base64-encoded-key-from-.env>  # Run: echo -n "your-app-key" | base64