# FINAL_DEV/terrain-booking-system/kubernetes/laravel-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  DB_HOST: "localhost"  # Pod-local MySQL
  DB_PORT: "3306"
  DB_DATABASE: "terrain_booking_db"
  APP_ENV: "production"kubectl port-forward <pod-name> 8080:8080